name: dedop
channels:
    - conda-forge
    - ccitools
    - defaults
dependencies:
    - python ==3.6
    - cate-util=1.1.0.dev1=py36_0
    - hdf4 ==4.2.12
    - netcdf4 ==1.2.4
    - numexpr ==2.6.4
    - numpy ==1.11.3
    - scipy ==1.0.0
    - bokeh ==0.12.13
    - ipywidgets ==7.1.1
    - jupyter ==1.0.0
    - matplotlib ==2.0.2
    - pyproj ==1.9.5.1
    - tornado >=4.0,<5.0
    #
    # for testing only
    #
    - pytest
    - pytest-cov